version: '3'

volumes:
  grafana-data:

services:
  statsd:
    build: 
      context: ./app/server/statsd
    ports:
      - 8125:8125/udp
      - 8126:8126/tcp
    external_links:
    - graphite_graphite_1:graphite
    volumes:
      - ./app/server/statsd/config.js:/opt/statsd/config.js
    restart: always

  statsd_exporter:
    image: prom/statsd-exporter
    container_name: statsd-exporter
    command: 
      - '--statsd.mapping-config=/tmp/statsd_mapping.yml'
      - '--statsd.listen-udp=:9125'
      - '--web.listen-address=:9102'
    ports:
      - 9123:9102
      - 9125:9125/udp
    volumes:
      - './app/server/statsd/statsd_mapping.yml:/tmp/statsd_mapping.yml'
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command: 
      - "--config.file=/tmp/prometheus.yml"
      - "--web.page-title='Metrics Collector Demo'"
      - '--web.listen-address=:9090'
    ports:
      - 9090:9090
    depends_on:
      - statsd_exporter
    volumes:
      - ./app/server/prometheus.yml:/tmp/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./app/server/grafana-provisioning/:/etc/grafana/provisioning
    restart: always
